#!/usr/bin/env srcery-bash

wt_path="${1:?usage: run WT_PATH}"
abs_wt_path=$(cd "$wt_path" && pwd -P)

srcery_new_window storybook "$abs_wt_path" make -C "$wt_path" storybook >/dev/null

cd "$wt_path" || exit
exec npm run dev
