#!/usr/bin/env srcery-bash

uuid="${1:?usage: @svc-logs UUID [out|err]}"
stream="${2:-out}"
svc_dir="$SRCERY_DATA/svcs/$uuid"

[[ -d "$svc_dir" ]] || die "no such service: $uuid"
[[ "$stream" == "out" || "$stream" == "err" ]] || die "stream must be 'out' or 'err'"

exec tail -f "$svc_dir/$stream"
