#!/usr/bin/env srcery-bash

wt_filter=""
name_filter=""

while [[ $# -gt 0 ]]; do
	case "$1" in
		-w) wt_filter="${2:?-w requires a pattern}"; shift 2 ;;
		-n) name_filter="${2:?-n requires a pattern}"; shift 2 ;;
		*)  die "usage: @svc-list [-w worktree-pattern] [-n name-pattern]" ;;
	esac
done

srcery_tmux has-session -t "=srcery" 2>/dev/null || exit 0

printf "%-6s %-15s %-20s %-8s %s\n" ID NAME WORKTREE STATUS PID

srcery_tmux list-windows -t "=srcery" -F '#{window_id} #{window_name} #{pane_current_path} #{pane_dead} #{pane_pid}' \
| while read -r win_id wname cwd pane_dead pane_pid; do
	[[ "$wname" != "_placeholder" ]] || continue

	wt_name=$(basename "$cwd")

	[[ -z "$wt_filter" ]]   || [[ "$wt_name" == *"$wt_filter"* ]] || continue
	[[ -z "$name_filter" ]] || [[ "$wname" == *"$name_filter"* ]]  || continue

	if [[ "$pane_dead" != "0" ]]; then
		status="dead"
	elif [[ -f "$SRCERY_DATA/status/$wt_name/$wname" ]]; then
		status=$(<"$SRCERY_DATA/status/$wt_name/$wname")
	else
		status="running"
	fi

	printf "%-6s %-15s %-20s %-8s %s\n" "$win_id" "$wname" "$wt_name" "$status" "$pane_pid"
done
