#!/usr/bin/env srcery-bash

win="${1:?usage: @svc-stop WINDOW}"

srcery_tmux has-session -t "=srcery" 2>/dev/null \
	|| die "no services running"

srcery_tmux list-windows -t "=srcery" -F '#{window_name}' \
	| grep -qxF "$win" \
	|| die "no such service: $win"

pid=$(srcery_tmux display-message -t "=srcery:=$win" -p '#{pane_pid}')
dead=$(srcery_tmux display-message -t "=srcery:=$win" -p '#{pane_dead}')

if [[ "$dead" == "1" ]]; then
	echo "already dead (pid $pid), cleaning up"
else
	echo "stopped $win (pid $pid)"
fi

srcery_tmux kill-window -t "=srcery:=$win"
