#!/usr/bin/env srcery-bash

wt_filter=""
name_filter=""

while [[ $# -gt 0 ]]; do
	case "$1" in
		-w) wt_filter="${2:?-w requires a pattern}"; shift 2 ;;
		-n) name_filter="${2:?-n requires a pattern}"; shift 2 ;;
		*)  die "usage: @svc-list [-w worktree-pattern] [-n name-pattern]" ;;
	esac
done

srcery_tmux has-session -t "=srcery" 2>/dev/null || exit 0

printf "%-30s %-8s %s\n" WINDOW STATUS PID

srcery_tmux list-windows -t "=srcery" -F '#{window_name} #{pane_dead} #{pane_pid}' \
| while read -r win pane_dead pane_pid; do
	[[ "$win" != "_placeholder" ]] || continue

	wt_name="${win%%/*}"
	svc_name="${win#*/}"

	[[ -z "$wt_filter" ]]   || [[ "$wt_name" == *"$wt_filter"* ]]   || continue
	[[ -z "$name_filter" ]] || [[ "$svc_name" == *"$name_filter"* ]] || continue

	if [[ "$pane_dead" != "0" ]]; then
		status="dead"
	elif [[ -f "$SRCERY_DATA/status/$win" ]]; then
		status=$(<"$SRCERY_DATA/status/$win")
	else
		status="running"
	fi

	printf "%-30s %-8s %s\n" "$win" "$status" "$pane_pid"
done
