#!/usr/bin/env srcery-bash

worktrees=()
first=true
while read -r name _rest; do
	$first && { first=false; continue; }  # skip header
	[[ -n "$name" ]] && worktrees+=("$name")
done < <(@wt-list)

[[ ${#worktrees[@]} -gt 0 ]] || { echo "no worktrees"; exit 0; }

echo "will remove ${#worktrees[@]} worktree(s):"
@wt-list >&2
read -rp "continue? [y/N] " answer
[[ "$answer" == [yY] ]] || die "aborted"

i=0
for wt in "${worktrees[@]}"; do
	@wt-remove "$wt"
	((++i))
	echo "[$i/${#worktrees[@]}] Removed $wt"
done
