#!/usr/bin/env bash
export PATH="$PATH:$SRCERY_ROOT/lib"
cd "$SRCERY_ROOT" || exit 1

export SRCERY_DATA="${SRCERY_DATA:-$SRCERY_ROOT/data}"

die() {
	>&2 echo "$@"
	exit 1
}
export -f die

export SRCERY_TMUX_SOCKET="${SRCERY_TMUX_SOCKET:-srcery}"

srcery_tmux() {
	command tmux -L "$SRCERY_TMUX_SOCKET" "$@"
}
export -f srcery_tmux

exec bash -euo pipefail "$@"
